### ISSUE TITLE
CFBundleVersion, not CFBundleShortVersionString should be used for validation

### ISSUE THREAD

**Issue by yyoo** [rmaddy/VerifyStoreReceiptiOS#1]
There are comments and an assertion in the code that the short bundle version string should be used.  This is true for OS X, but not for iOS.  The regular bundle version string must be used in iOS.

**Comment by rmaddy** [comment]
I'm using CFBundleShortVersionString in my iOS app and it works just fine. But my regular version and short version are always the same in my Info.plist. So I'm not sure which is correct for iOS.

**Comment by yyoo** [comment]
Check out Apple's latest documentation on the receipt fields.  It's regular version string for iOS, short version string for OS X.  We've also confirmed it in our testing.  Our app has always had different values for short and regular, and validation was failing when we used short and worked fine when we used regular. 

You can play around with the values in the Info.plist of your own app to test this yourself.

**Comment by rmaddy** [comment]
Thanks. I believe you are correct. It will be a day or two before I can update the code.

**Comment by kabucey** [comment]
I got bit by this bug as my short version was 1.2 and the longer version was 1.2.0.

**Comment by tomasikp** [comment]
@rmaddy

**Comment by drallgood** [comment]
@rmaddy Any timeframe as to when this will be fixed?

**Comment by mike-ferenduros** [comment]
Also got hit by this, just had to pull an app update from the store and submit an expedited update :(

Increasingly likely to happen since the recent iTunes Connect update - if you submit a build, reject it, then resubmit, iTC insists on a new version-string for the new build, making it more likely that people will use differing short and long version strings.

**Comment by rmaddy** [comment]
Fixed
