### ISSUE TITLE
Crash on PKCS7_verify

### ISSUE THREAD

**Issue by kashifhisam** [rmaddy/VerifyStoreReceiptiOS#11]
I am receiving too many crashes on 'PKCS7_verify' line. My project is non-ARC. I have edited most of the release calls myself but I think I missed some. Can anyone provide non-ARC code?

**Comment by designatednerd** [comment]
You should be able to use this in an ARC project without having to add the retain/release calls yourself by flagging the files as `fobjc-arc`. More info on where to do this: http://www.codeography.com/2011/10/10/making-arc-and-non-arc-play-nice.html

**Comment by kashifhisam** [comment]
Is there any way to do it other way around, i.e., using this ARC file in a non-ARC project

**Comment by designatednerd** [comment]
Yes, `fobjc-arc` is the command to use an ARC file in a non-ARC project. `fno-objc-arc` is the command to use a non-ARC file in an ARC project.

**Comment by kashifhisam** [comment]
Thanks, I will try this

**Comment by kashifhisam** [comment]
As per my findings, that problem was not related to ARC. I compiled libssl.a & libcrypto.a separately using another github project named 'OpenSSL-for-iPhone'. Then I used those libs in my project and now this issue seems to disappear.
