### ISSUE TITLE
Change of CFBundleShortVersionString to CFBundleVersion only in demo project

### ISSUE THREAD

**Issue by DerLobi** [rmaddy/VerifyStoreReceiptiOS#14]
Hi there,

the changes in 90f5c087d61644bb74d43d1dbb2c86f1fc0a09ad are only applied to `VerifyStoreReceipt/VerifyStoreReceipt.m` (in the demo project), not to `VerifyStoreReceipt.m` in the root directory.

**Comment by LukasCZ** [comment]
Yes!! This is exactly why I am now with broken release in the App Store. I've waited two weeks for the app to get approved, and now the validation always fails because the build id is different from the short version string!!

**Comment by rmaddy** [comment]
I've updated the other copy of the file.
