### ISSUE TITLE
Is the newly discovered openssl vulnerability something to worry about?

### ISSUE THREAD

**Issue by yyoo** [rmaddy/VerifyStoreReceiptiOS#8]
Do we need to link with the latest version of the openssl?  (1.0.1g)

**Comment by rmaddy** [comment]
This is a good question. I honestly don't know what impact the OpenSSL bug would have. Probably little since OpenSSL is not being used here in a way that would allow an attacker to access anything. But it's always a good idea to use the latest tools when security is involved.
